// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tygnvbzfwenscbsnvbhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5Z252Ynpmd2Vuc2Nic252YmhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzEwMjQsImV4cCI6MjA3MTIwNzAyNH0.OnIB3tnUqeVAkckBRlpJ0r3Cl5cEYT3_waSHd0j8Ozk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});